# Sample Node.js app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            - containerPort: 3000
          # Exactly the same as the Deployment config
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  # Secret config filename
                  name: mongo-secret
                  key: mongo-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  # ConfigMap config filename
                  name: mongo-config
                  key: mongo-url

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  # By default, Services are type `ClusterIP` (internal) 
  # Use an external service type like `NodePort`
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # NodePort opens on K8s Nodes
      # Anything between 30000-32767 is valid
      nodePort: 30100
